
import java.awt.Color;
import java.io.File;
import java.sql.*;
import java.text.SimpleDateFormat;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author lenovo
 */
public class PatientRegistration extends javax.swing.JFrame {
    public String emailPattern = "^(?=.{1,64}@)[A-Za-z0-9_-]+(\\.[A-Za-z0-9_-]+)*@" + "[^-][A-Za-z0-9-]+(\\.[A-Za-z0-9-]+)*(\\.[A-Za-z]{2,})$";
    public String mobilenumberPattern="^[0-9]*$";
            


    /**
     * Creates new form PatientRegistration
     */
    public PatientRegistration() {
        
        initComponents();
        try
        {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/ehealthcare","root","");
            JOptionPane.showMessageDialog(null,"Connected");        
        }
        catch(Exception e)
        {
          JOptionPane.showMessageDialog(null,"Not Connected");
        }
       
    }
    


    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        dob = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        male = new javax.swing.JRadioButton();
        female = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        mobileno = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        address = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        location = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        disabledyes = new javax.swing.JRadioButton();
        disabledno = new javax.swing.JRadioButton();
        aadhaarpath = new javax.swing.JTextField();
        aadhaar = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        jLabel13 = new javax.swing.JLabel();
        confirmpassword = new javax.swing.JPasswordField();
        jLabel14 = new javax.swing.JLabel();
        photo = new javax.swing.JButton();
        submit = new javax.swing.JButton();
        bloodgroup = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Stencil", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(249, 0, 0));
        jLabel1.setText("PATIENT REGISTRATION");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 22, 611, 59));

        jLabel2.setText("FULL NAME      *");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 127, 301, 36));

        name.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 4, 4, new java.awt.Color(102, 0, 102)));
        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nameKeyReleased(evt);
            }
        });
        getContentPane().add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 169, 275, 32));

        jLabel3.setText("DATE OF BIRTH");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(496, 127, 262, -1));
        getContentPane().add(dob, new org.netbeans.lib.awtextra.AbsoluteConstraints(496, 169, 250, 32));

        jLabel4.setText("GENDER");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 230, 275, 26));

        buttonGroup1.add(male);
        male.setText("Male");
        male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleActionPerformed(evt);
            }
        });
        getContentPane().add(male, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 274, -1, -1));

        buttonGroup1.add(female);
        female.setText("Female");
        female.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femaleActionPerformed(evt);
            }
        });
        getContentPane().add(female, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 274, -1, -1));

        jLabel5.setText("MOBILE NUMBER         *");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 323, 275, 26));

        mobileno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                mobilenoKeyReleased(evt);
            }
        });
        getContentPane().add(mobileno, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 355, 275, 34));

        jLabel6.setText("BLOOD GROUP        *");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 230, 250, -1));

        jLabel7.setText("EMAIL *");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(496, 328, 50, -1));

        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });
        email.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                emailKeyReleased(evt);
            }
        });
        getContentPane().add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(496, 355, 250, 34));

        jLabel8.setText("ADDRESS");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 407, 275, -1));
        getContentPane().add(address, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 441, 275, 156));

        jLabel9.setText("LOCATION");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(496, 407, 250, -1));
        getContentPane().add(location, new org.netbeans.lib.awtextra.AbsoluteConstraints(496, 441, 250, 35));

        jLabel10.setText("ARE YOU DISABLED?");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(496, 494, 250, 25));

        buttonGroup2.add(disabledyes);
        disabledyes.setText("YES");
        disabledyes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                disabledyesActionPerformed(evt);
            }
        });
        getContentPane().add(disabledyes, new org.netbeans.lib.awtextra.AbsoluteConstraints(496, 537, -1, -1));

        buttonGroup2.add(disabledno);
        disabledno.setText("NO");
        disabledno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                disablednoActionPerformed(evt);
            }
        });
        getContentPane().add(disabledno, new org.netbeans.lib.awtextra.AbsoluteConstraints(556, 537, -1, -1));
        getContentPane().add(aadhaarpath, new org.netbeans.lib.awtextra.AbsoluteConstraints(496, 648, 250, 62));

        aadhaar.setBackground(new java.awt.Color(0, 204, 255));
        aadhaar.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        aadhaar.setText("ATTACH AADHAAR");
        aadhaar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aadhaarActionPerformed(evt);
            }
        });
        getContentPane().add(aadhaar, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 648, 275, 62));

        jLabel12.setText("PASSWORD    *");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(864, 127, 251, -1));
        getContentPane().add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(864, 179, 225, -1));

        jLabel13.setText("CONFIRM PASSWORD  *");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 230, 140, -1));
        getContentPane().add(confirmpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(864, 274, 225, -1));
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(864, 323, -1, -1));

        photo.setBackground(new java.awt.Color(255, 255, 102));
        photo.setFont(new java.awt.Font("Stencil", 1, 14)); // NOI18N
        photo.setText("GO TO HOME");
        photo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                photoActionPerformed(evt);
            }
        });
        getContentPane().add(photo, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 440, 143, 107));

        submit.setBackground(new java.awt.Color(102, 0, 102));
        submit.setFont(new java.awt.Font("Stencil", 1, 36)); // NOI18N
        submit.setForeground(new java.awt.Color(255, 255, 153));
        submit.setText("SUBMIT");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });
        getContentPane().add(submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(887, 595, 190, 115));

        bloodgroup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bloodgroupActionPerformed(evt);
            }
        });
        getContentPane().add(bloodgroup, new org.netbeans.lib.awtextra.AbsoluteConstraints(496, 274, 250, 31));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/PatientRegistration.jpg"))); // NOI18N
        jLabel11.setText("jLabel11");
        jLabel11.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jLabel11KeyReleased(evt);
            }
        });
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jButton1.setText("jButton1");
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 600, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void photoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_photoActionPerformed
/*        // TODO add your handling code here:
        JFileChooser ph=new JFileChooser();
        ph.showOpenDialog(null);
        File f=ph.getSelectedFile();
        String filename=f.getAbsolutePath();
        photopath.setText(filename);*/
HomePage p=new HomePage();
p.show();
dispose();
    }//GEN-LAST:event_photoActionPerformed

    private void aadhaarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aadhaarActionPerformed
        // TODO add your handling code here:
        JFileChooser aad=new JFileChooser();
        aad.showOpenDialog(null);
        File fa=aad.getSelectedFile();
        String filenamea=fa.getAbsolutePath();
        aadhaarpath.setText(filenamea);
    }//GEN-LAST:event_aadhaarActionPerformed

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat d=new SimpleDateFormat();
        String dateofbirt=d.format(dob.getDate());
        try 
        {
           // Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/ehealthcare","root","");
            Statement stmt = con.createStatement(); 
            // Inserting data in database
            String s="";
            if((name.getText()).equals(s))
                JOptionPane.showMessageDialog(null,"ENTER THE NAME");
            if(gender==null)
                JOptionPane.showMessageDialog(null,"CHOOSE GENDER");
            if((mobileno.getText()).equals(s))
                JOptionPane.showMessageDialog(null,"PROVIDE MOBILE NUMBER");
            
            pwd = new String(password.getPassword());
            cp=new String(confirmpassword.getPassword());
            if(!pwd.equals(cp))
            {
                JOptionPane.showMessageDialog(null,"PASSWORD AND CONFIRM PASSWORD ARE CONTRARY");
            }
            String h=email.getText();
            if(h.indexOf("@gmail.com")==-1)
            {
                JOptionPane.showMessageDialog(null,"VALID MAIL");
            }
            else
            {
            String q1 = "insert into patient values('" +name.getText()+"','"+gender+"','"+mobileno.getText()+"','"+address.getText()+"','"+dateofbirt+"','"+bloodgroup.getText()+"','"+email.getText()+"','"+location.getText()+"','"+disabled+"','"+pwd+"')";
            stmt.executeUpdate(q1);
            JOptionPane.showMessageDialog(null,"THANK YOU \n"+name.getText()+"\n FOR REGISTERING TO OUR SERVICE!!LOGIN TO KNOW MORE ABOUT US!!!");
            Email m=new Email();
            String mai=email.getText();
            String n=name.getText();
        m.createAndSendEmail("jeevajoslinehealthcareservice@gmail.com", "",
      "HI!!!"+n+""
              + " \r\n THANK YOU  FOR REGISTERING TO OUR SERVICE LOGIN TO KNOW OUR FEATURES WE WISH YOU A HAPPY AND HEALTHY LIFE",mai);
            SignIn i=new SignIn();
            i.show();
            dispose();
            }
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
                                       

        
        
    }//GEN-LAST:event_submitActionPerformed

    private void femaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femaleActionPerformed
        // TODO add your handling code here:
        gender="Female";
    }//GEN-LAST:event_femaleActionPerformed

    private void maleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleActionPerformed
        // TODO add your handling code here:
        gender="Male";
    }//GEN-LAST:event_maleActionPerformed

    private void disabledyesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_disabledyesActionPerformed
        // TODO add your handling code here:
        disabled="Yes";
    }//GEN-LAST:event_disabledyesActionPerformed

    private void disablednoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_disablednoActionPerformed
        // TODO add your handling code here:
        disabled="No";
    }//GEN-LAST:event_disablednoActionPerformed

    private void nameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameKeyReleased
        // TODO add your handling code here:
       String na=name.getText();
       if(na.matches(""))
       {
           name.setBackground(Color.red);
           JOptionPane.showMessageDialog(null,"Enter your Name");
       }
       else
        {
            name.setBackground(Color.white);
        }
    }//GEN-LAST:event_nameKeyReleased

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    private void bloodgroupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bloodgroupActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bloodgroupActionPerformed

    private void jLabel11KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel11KeyReleased
        // TODO add your handling code here:
        String bg=jLabel11.getText();
       if(bg.matches(""))
       {
           jLabel11.setBackground(Color.red);
           JOptionPane.showMessageDialog(null,"Enter the blood group");
       }
       else
        {
            jLabel11.setBackground(Color.white);
        }
    }//GEN-LAST:event_jLabel11KeyReleased

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void emailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_emailKeyReleased
        // TODO add your handling code here:
        String em=email.getText();
       if(em.matches(""))
       {
           email.setBackground(Color.red);
           JOptionPane.showMessageDialog(null,"Enter the email id");
       }
       else
        {
            email.setBackground(Color.white);
        }
    }//GEN-LAST:event_emailKeyReleased

    private void mobilenoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mobilenoKeyReleased
        // TODO add your handling code here:
        String con=mobileno.getText();
        if(con.matches("[0-9]*$") && con.length()==10)
        {
            mobileno.setBackground(Color.green);
            JOptionPane.showMessageDialog(null,"Valid number");
        }
        else if(con.matches(""))
        {
            mobileno.setBackground(Color.pink);
            JOptionPane.showMessageDialog(null,"Enter the contact number");
        }
        else
        {
            mobileno.setBackground(Color.red);
        }
    }//GEN-LAST:event_mobilenoKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PatientRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PatientRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PatientRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PatientRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PatientRegistration().setVisible(true);
                
            }
        });
    }
    private String gender;
    String dateofbirth;
    String disabled;
    String pwd;
    String cp;
        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aadhaar;
    private javax.swing.JTextField aadhaarpath;
    private javax.swing.JTextField address;
    private javax.swing.JTextField bloodgroup;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JPasswordField confirmpassword;
    private javax.swing.JRadioButton disabledno;
    private javax.swing.JRadioButton disabledyes;
    private com.toedter.calendar.JDateChooser dob;
    private javax.swing.JTextField email;
    private javax.swing.JRadioButton female;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField location;
    private javax.swing.JRadioButton male;
    private javax.swing.JTextField mobileno;
    private javax.swing.JTextField name;
    private javax.swing.JPasswordField password;
    private javax.swing.JButton photo;
    private javax.swing.JButton submit;
    // End of variables declaration//GEN-END:variables
}
