
import java.lang.System.Logger;
import java.lang.System.Logger.Level;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import java.util.*;
import java.lang.*;
import java.util.HashMap;
import javax.swing.*;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author lenovo
 */
public class Pharmacy extends javax.swing.JFrame {
    private String n,e;
    /**
     * Creates new form Pharmacy
     */
    public Pharmacy(String a,String b) {
        initComponents();
        n=a;
        e=b;
        
    }
    DefaultTableModel model=new DefaultTableModel();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        addbutton = new javax.swing.JButton();
        printbill = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        subtot = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        pay = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        balance = new javax.swing.JTextField();
        tablet = new javax.swing.JSpinner();
        ck1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jSpinner2 = new javax.swing.JSpinner();
        jSpinner3 = new javax.swing.JSpinner();
        jSpinner4 = new javax.swing.JSpinner();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("MV Boli", 1, 48)); // NOI18N
        jLabel1.setText("E-PHARMACY");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 0, 351, 98));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "MEDICINE", "PRICE", "QUANTITY", "TOTAL"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 110, 365, 287));

        addbutton.setText("ADD");
        addbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(addbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 390, 91, 36));

        printbill.setText("PRINT BILL");
        printbill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printbillActionPerformed(evt);
            }
        });
        getContentPane().add(printbill, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 450, 201, 45));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("SUB TOTAL");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 140, -1, -1));
        getContentPane().add(subtot, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 140, 197, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("PAY");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 180, -1, -1));

        pay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payActionPerformed(evt);
            }
        });
        getContentPane().add(pay, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 180, 197, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("BALANCE");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 230, -1, -1));
        getContentPane().add(balance, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 230, 197, -1));
        getContentPane().add(tablet, new org.netbeans.lib.awtextra.AbsoluteConstraints(286, 112, 140, 30));

        ck1.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        ck1.setText("Paracetamol");
        ck1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ck1ActionPerformed(evt);
            }
        });
        getContentPane().add(ck1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 147, -1));

        jCheckBox2.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jCheckBox2.setText("Bandages");
        getContentPane().add(jCheckBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, 130, -1));
        getContentPane().add(jSpinner2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 250, 140, 30));
        getContentPane().add(jSpinner3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, 140, 30));
        getContentPane().add(jSpinner4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 320, 140, 30));

        jCheckBox3.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jCheckBox3.setText("Oilment");
        getContentPane().add(jCheckBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, -1, -1));

        jCheckBox4.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jCheckBox4.setText("Syrup");
        getContentPane().add(jCheckBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 320, -1, -1));

        jButton1.setText("BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 14, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pharmacy yellow.png"))); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void payActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_payActionPerformed

    private void ck1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ck1ActionPerformed






        // TODO add your handling code here:
    }//GEN-LAST:event_ck1ActionPerformed

    private void addbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbuttonActionPerformed
        // TODO add your handling code here:
        
        int sum=0;
        int price;
        int qty;
        int tot;
        if(ck1.isSelected())
        {
            String tab=ck1.getText();
            price=10;
            qty=Integer.parseInt(tablet.getValue().toString());
            tot=price*qty;
            model=(DefaultTableModel)jTable1.getModel();
            model.addRow(new Object[]
            {
                tab,
                price,
                qty,
                tot
            });
                    
        }
        if(jCheckBox2.isSelected())
        {
            String band =jCheckBox2.getText();
            price=30;
            qty=Integer.parseInt(jSpinner2.getValue().toString());
            tot=price*qty;
            model=(DefaultTableModel)jTable1.getModel();
            model.addRow(new Object[]
            {
                band,
                price,
                qty,
                tot
            });
                    
        }
        if(jCheckBox3.isSelected())
        {
            String oil=jCheckBox3.getText();
            price=150;
            qty=Integer.parseInt(jSpinner3.getValue().toString());
            tot=price*qty;
            model=(DefaultTableModel)jTable1.getModel();
            model.addRow(new Object[]
            {
                oil,
                price,
                qty,
                tot
            });
                    
        }
        if(jCheckBox4.isSelected())
        {
            String syru=jCheckBox4.getText();
            price=90;
            qty=Integer.parseInt(jSpinner4.getValue().toString());
            tot=price*qty;
            model=(DefaultTableModel)jTable1.getModel();
            model.addRow(new Object[]
            {
                syru,
                price,
                qty,
                tot
            });
                    
        }
        for(int i=0;i<jTable1.getRowCount();i++)
        {
            sum=sum+Integer.parseInt(jTable1.getValueAt(i,3).toString());
        }
        
        subtot.setText(String.valueOf(sum));
        
    }//GEN-LAST:event_addbuttonActionPerformed

    public void sales()
    {
        try
        {
               String sub=subtot.getText();
               String p=pay.getText();
               String bal=balance.getText();
               int lastid=0;
        
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/ehealthcare","root","");
            String q1 = "insert into pharma(subtotal,pay,balance)values(?,?,?)";
            PreparedStatement  ps1=con.prepareStatement(q1,Statement.RETURN_GENERATED_KEYS);
            PreparedStatement ps2;
            ps1.setString(1,sub);
            ps1.setString(2,p);
            ps1.setString(3,bal);
            ps1.executeUpdate();
            ResultSet rs = ps1.getGeneratedKeys();
            
            if(rs.next())
            {
                lastid = rs.getInt(1);
            }
            int rows = jTable1.getRowCount();
            
            String query1 = "insert into pharmacysales(sales_id,medicine,qty,price,total)values(?,?,?,?,?)";
            ps2 = con.prepareStatement(query1);
            
            String medicine = "";
            int price;
            int qty;
            int total = 0;
            
            for(int i=0; i<jTable1.getRowCount(); i++)
            {
                medicine = (String)jTable1.getValueAt(i, 0);
                price = (int)jTable1.getValueAt(i, 1);
                qty = (int)jTable1.getValueAt(i, 2);
                total = (int)jTable1.getValueAt(i, 3);
                 ps2.setInt(1,lastid);
                 ps2.setString(2,medicine);
                 ps2.setInt(3,qty);
                 ps2.setInt(4,price);
                 ps2.setInt(5,total);
                 ps2.executeUpdate();
            }
            JOptionPane.showMessageDialog(this,"THANK YOU "+n+" FOR PURCHASING ,CHECK YOUR MAIL FOR FURTHER DETAILS");
            JOptionPane.showMessageDialog(this, "Wait for receipt!!!");
            /*Email m=new Email();
            m.createAndSendEmail("jeevajoslinehealthcareservice@gmail.com", "","HELLO  "+n+
      "THANK YOU FOR CHOOSING OUR E-PHARMACY "+"<br>"+" \r\nAND THANK YOU "+n+" FOR PURCHASING ,WE WISH YOU A HAPPY AND HEALTHY LIFE",e);
            
            JOptionPane.showMessageDialog(this,"CHECK YOUR MAILBOX");*/
            HashMap a = new HashMap();
                    a.put("invo", lastid);
            
            try {
                JasperDesign jdesign = JRXmlLoader.load("C:\\Users\\lenovo\\Documents\\NetBeansProjects\\E-HealthCareManagementSystem\\src\\ehealthreport\\report2.jrxml");
                JasperReport jreport = JasperCompileManager.compileReport(jdesign);
                
                JasperPrint jprint = JasperFillManager.fillReport(jreport, a,con);
                
                JasperViewer.viewReport(jprint);
            } 
            /*/catch (JRException ex) {
                Logger.getLogger(movieticket.class.getName()).log(Level.SEVERE, null, ex);
            }/*/
            catch(JRException e)
            {
                JOptionPane.showMessageDialog(null,e);
            }
        }
 
        catch (Exception ex) {
            JOptionPane.showMessageDialog(null,ex);
        }    
        }
    private void printbillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printbillActionPerformed
        // TODO add your handling code here:
        
        int sub = Integer.parseInt(subtot.getText());
        int payy = Integer.parseInt(pay.getText());
        int bal = payy - sub;
        balance.setText(String.valueOf(bal));
        sales();
 
    }//GEN-LAST:event_printbillActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
MainPage m=new MainPage(n,e);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pharmacy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pharmacy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pharmacy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pharmacy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pharmacy().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addbutton;
    private javax.swing.JTextField balance;
    private javax.swing.JCheckBox ck1;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JSpinner jSpinner3;
    private javax.swing.JSpinner jSpinner4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField pay;
    private javax.swing.JButton printbill;
    private javax.swing.JTextField subtot;
    private javax.swing.JSpinner tablet;
    // End of variables declaration//GEN-END:variables
}
